### ISSUE TITLE
Add support for CSS templates (e.x. automatically center an element)

### ISSUE THREAD

**Issue by duttpatel** [Raathigesh/fabulous#11]
I like the concept. But I am looking for in build template like centering the element. If this could you include in your project that will be great.

**Comment by Raathigesh** [comment]
I assume it could get complicated if we go that way because the Fabulous then needs to know about CSS rules and how they work together. or Maybe I'm wrong. 

Feel free to share your thoughts!

**Comment by Raathigesh** [comment]
I'm closing this for the time being. Please feel free to re-open if you have more ideas.
