### ISSUE TITLE
Support for Angular inline CSS

### ISSUE THREAD

**Issue by paustint** [Raathigesh/fabulous#13]
I just saw you featured on Changelog Nightly - that is how I found out about this library - http://nightly.changelog.com/2019/05/29/  🎉 

**Is your feature request related to a problem? Please describe.**
Angular 8 allows CSS to be included in a component as a CSS-in-JS sort of flavor, and it would be create if Fabulous supported this.

The structure is this:
1. it is always a typescript file
1. The file will always be named with a suffix of `.component.ts`, example `app.component.ts` or `foo-bar.component.ts`
1. There is a class decorator named `@Component({})` which has an optional `styles` array that can have one or more multi-line strings that are CSS classes
    - In practice, people do not have more than multi-line string.
    - The styles array is optional and may not exist.

**Additional context**
Take a look at a code example below

```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app-my-component',
  templateUrl: './app-my-component.html',
  styles: [
    `
      .exists-label {
        width: 115px;
        display: inline-block;
      }
      .btn-all-diffs {
        min-width: 130px;
      }
      .sticky-bottom {
        position: fixed; /* Fixed/sticky position */
        bottom: 50px; /* Place the button at the bottom of the page */
        right: 30px; /* Place the button 30px from the right */
        z-index: 99; /* Make sure it does not overlap */
      }
      .show {
        display: block;
      }
      .hide {
        display: none;
      }
    `,
  ],
})
export class MyComponent {
...
}
```

**Comment by Raathigesh** [comment]
Thank you for the detailed issue. Would you be able to help out with this feature?

**Comment by Raathigesh** [comment]
Also thanks for letting me know about the changelog nightly. It's nice to be featured there :)

**Comment by paustint** [comment]
I think that I could probably help out with this feature. I first need to learn the codebase and figure out how it works, then I can give it a shot. I will put it on my list of things to do. :)

**Comment by Raathigesh** [comment]
Thank you for doing this. If you are interested in contributing, let me know so I can invite you as a collaborator 👍 

I'll try to release this by this weekend along with some other changes.

**Comment by paustint** [comment]
Awesome! Thank you so much. I think the readme should be updated as well to
indicate support for this, as o forgot to do that.

**Comment by paustint** [comment]
> Thank you for doing this. If you are interested in contributing, let me know so I can invite you as a collaborator 👍

@Raathigesh - yes, I am interesting in contributing on an ongoing basis and would very much like to be a contributor.
