### ISSUE TITLE
Add fabulous to HTML files.

### ISSUE THREAD

**Issue by s0kil** [Raathigesh/fabulous#14]
**Is your feature request related to a problem? Please describe.**
Why does't it also work in HTML files, for example having a `style` tag in html

**Describe the solution you'd like**
Enable fabulous to work in HTML files

**Comment by paustint** [comment]
@s0kil - Thank you for the suggestion. I have just submitted a PR with support for HTML files.
https://github.com/Raathigesh/fabulous/pull/21

With the PR, support is added for style tags as long as they follow on of the following formats:

**Style tab nested in the head tag**
```html
<html>
    <head>
        <style>
          /** STYLES HERE */
        </style>
    </head>
</html>
```

**Style tag in root of file (to support vue/svelte)**
```html
<style>
/** STYLES HERE */
</style>
```
