### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by paustint** [Raathigesh/fabulous#16]
**Is your feature request related to a problem? Please describe.**
This project should contain a changelog to document the changes over time with versions.

**Comment by Raathigesh** [comment]
It's a good idea. Usually, as I merge changes, I keep a new release note in draft status and add the pull requests there and manually create a release note when I release.

Are you thinking about adding a ChangeLog.md to the repo?

**Comment by paustint** [comment]
I was suggestion a changlog.md, as most open source repositories follow
that pattern, but it is your decision. :)
