### ISSUE TITLE
Add CI to run tests

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/fabulous#25]
We have to enable tests to run in CI - https://code.visualstudio.com/api/working-with-extensions/continuous-integration

**Comment by paustint** [comment]
This ticket was completed with PR #24 - we can close this ticket.

https://travis-ci.org/Raathigesh/fabulous/jobs/541031782

![image](https://user-images.githubusercontent.com/5461649/58846405-4d9ff880-863c-11e9-9178-d51c3808aede.png)
