### ISSUE TITLE
Support for .less and .css (when language mode = PostCSS)

### ISSUE THREAD

**Issue by tbb2** [Raathigesh/fabulous#7]
I'd love to see support for .less files - and especially for .css files when language mode is set to PostCSS, that doesn't work for me (I have set it in general, that .css files should have this language mode))

**Comment by Raathigesh** [comment]
I'm not familiar with language mode. Could you please elaborate?

**Comment by tbb2** [comment]
You can see language mode in the lower right corner:
![image](https://user-images.githubusercontent.com/5879301/58548717-2c897300-820a-11e9-942a-dd22308214fa.png)

and in my settings.json I have this:
`  "files.associations": {
    "*.css": "postcss"
  },`

**Comment by Raathigesh** [comment]
got it. It would also be helpful a small snippet which fails in fabulous when the language mode is set to postcss.

**Comment by tbb2** [comment]
I just open a css-file, and the fabulous-icon-button doesn't appear. It appears if I open .js files for instance. 
I think it's because I changed the file association in my settings, because if I change language mode using the menu in the lower right corner, the fabulous-icon-button still doesn't appear.
The reason why I use this file association is that I want to use the newest css and therefore I want postCSS because the syntax highlighting from just plain css is not good enough for postCSS.

**Comment by Raathigesh** [comment]
I just published a newer version (0.10.0) to the marketplace which should support postcss language mode. It might take a while for the newer version to appear in the marketplace though.

**Comment by tbb2** [comment]
Super, it's working for postcss, thanks 👍 :-)

**Comment by Skaidon** [comment]
@Raathigesh any chance we can get support for `.less` files?

**Comment by Raathigesh** [comment]
My immediate focus is to enhance the current functionality and doesn't have plans to implement `.less` support anytime soon. That being said, I'm more than happy to help if you want to contribute LESS support. We use [Postcss](https://github.com/postcss/postcss) as the parser and if they support LESS, then we should be able to integrate it fairly easily.
